version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - sam package --s3-bucket $BUCKET --output-template-file package.yaml
artifacts:
  files:
    - package