version: 1.0.0
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - sam build && sam package --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml