version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file package.yaml
artifacts:
  files:
    - package.yaml