AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Dummy AWS Lambda Function

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody: >
        openapi: 3.0.3
        info:
          title: Hello World
          description: Hello World
          version: 1.0.0
        paths:
          /hello:
            get:
              responses:
                '200':
                  description: success
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          message:
                            type: string

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.handler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref HelloWorldApi