openapi: 3.0.3
info:
  title: Hello World
  description: Hello World
  version: 1.0.0
paths:
  /hello:
    get:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      x-amazon-apigateway-integration:
        type: aws
        httpMethod: POST
        uri: arn:aws:apigateway:eu-west-2:lambda:path/arn:aws:lambda:eu-west-2:132060109857:function:lambda-pipeline-stack-HelloWorldFunction-1J1EP5UEVI62L
        credentials: arn:aws:iam::132060109857:role/apigateway-invoke-lambda-exec-role