openapi: 3.0.3
info:
  title: Hello World
  description: Hello World
  version: 1.0.0
paths:
  /hello:
    get:
      responses:
        default:
          description: success
          content:
            application/json:
              schema:
                type: object