openapi: 3.0.3
info:
  title: Hello World
  description: Hello World
  version: 1.0.0
paths:
  /hello:
    get:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${!Ref HelloWorldFunction}/invocations
        credentials:
          Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/apigateway-invoke-lambda-exec-role