openapi: 3.0.3
info:
  title: Hello World
  description: Hello World
  version: 1.0.0
paths:
  /hello:
    get:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      x-amazon-apigateway-integration:
        type: aws
        httpMethod: POST
        uri: !Join [ ':', [ 'arn:aws:lambda' , !Ref AWS::Region ] ]